# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-26 22:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u8d2d\u4e70\u65f6\u95f4')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='\u8bfe\u7a0b\u540d\u79f0')),
                ('price', models.IntegerField(default=0, verbose_name='\u4ef7\u683c')),
                ('learn_time', models.CharField(max_length=6, verbose_name='\u5b66\u4e60\u65f6\u957f')),
                ('nums', models.IntegerField(default=0, verbose_name='\u8d2d\u4e70\u4eba\u6570')),
                ('image', models.ImageField(upload_to='img/%Y/%m', verbose_name='\u5c01\u9762\u56fe')),
                ('describe', models.ImageField(upload_to='img/course/%Y/%m', verbose_name='\u63cf\u8ff0')),
                ('click_num', models.IntegerField(default=0, verbose_name='\u70b9\u51fb\u4eba\u6570')),
            ],
            options={
                'verbose_name': '\u8bfe\u7a0b',
                'verbose_name_plural': '\u8bfe\u7a0b',
            },
        ),
        migrations.CreateModel(
            name='CourseClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('it', 'IT\u4e92\u8054\u7f51'), ('language', '\u8bed\u8a00\u7559\u5b66'), ('design', '\u521b\u610f\u8bbe\u8ba1'), ('life', '\u5174\u8da3\u751f\u6d3b'), ('plant', '\u751f\u4ea7\u79cd\u690d'), ('edu', '\u5347\u5b66\u8003\u7814'), ('certificate', '\u516c\u57f9\u8003\u8bc1')], max_length=15, verbose_name='\u5206\u7c7b')),
            ],
            options={
                'verbose_name': '\u7b2c\u4e00\u5206\u7c7b',
                'verbose_name_plural': '\u7b2c\u4e00\u5206\u7c7b',
            },
        ),
        migrations.CreateModel(
            name='CourseSort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u7b2c\u4e8c\u5206\u7c7b')),
                ('classes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.CourseClass', verbose_name='\u7b2c\u4e00\u5206\u7c7b')),
            ],
            options={
                'verbose_name': '\u7b2c\u4e8c\u5206\u7c7b',
                'verbose_name_plural': '\u7b2c\u4e8c\u5206\u7c7b',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='\u8bfe\u7a0b\u540d')),
                ('start_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u5f00\u59cb\u65f6\u95f4')),
                ('end_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u7ed3\u675f\u65f6\u95f4')),
                ('lesson_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Course', verbose_name='\u8bfe\u7a0b')),
            ],
            options={
                'verbose_name': '\u7ae0\u8282',
                'verbose_name_plural': '\u7ae0\u8282',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=30, verbose_name='\u8001\u5e08\u540d')),
                ('teacher_des', models.CharField(max_length=100, verbose_name='\u8001\u5e08\u63cf\u8ff0')),
                ('teacher_img', models.ImageField(upload_to='img/tea/&Y/%m', verbose_name='\u8001\u5e08\u56fe')),
                ('teacher_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Course', verbose_name='\u8bfe\u7a0b\u540d')),
            ],
            options={
                'verbose_name': '\u8001\u5e08',
                'verbose_name_plural': '\u8001\u5e08',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='sort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.CourseSort', verbose_name='\u5206\u7c7b'),
        ),
        migrations.AddField(
            model_name='buy',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Course', verbose_name='\u8bfe\u7a0b'),
        ),
    ]
